project_name: youtube-video-summary

before:
  hooks:
  - sh -c "mkdir -p cmd/server/dist && cd web && bun install && bun run build && cp -rv dist/* ./../cmd/server/dist/"

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    dir: .
    main: ./cmd/server
    binary: youtube-video-summary
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dist: dist

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip