project_name: youtube-video-summary

before:
  hooks:
    - mkdir -p cmd/server/dist && cd web && bun install && bun run build && cd .. && cp -rv web/dist/* cmd/server/dist/

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    dir: .
    main: ./cmd/server
    binary: youtube-video-summary
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

dist: dist