name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.23.x
        os:
          - ubuntu

    name: build (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Build frontend
      run: |
        cd web
        bun install
        bun run build
        cd ..
        mkdir -p cmd/server/dist
        cp -rv web/dist/* cmd/server/dist/
    
    - run: make build

  qa:
    strategy:
      matrix:
        go-version:
          - 1.23.x
        os:
          - ubuntu

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - run: make check-fmt
    - run: make vet
    - run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - run: make staticcheck
    - run: go install mvdan.cc/unparam@latest
    - run: make unparam

  test:
    needs: qa
    strategy:
      matrix:
        go-version:
          - 1.23.x
        os:
          - ubuntu

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - run: make test SKIP_INTEGRATION=true