name: goreleaser
on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 'latest'
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}